print(3*'=','Dissecando uma variável',3*'=')
print()
thing = input('Escreva algo: ')
print()
print(f'Tipo: {type(thing)}')
print(f'Existe apenas espaços: {thing.isspace()}')
print(f'É numérico: {thing.isnumeric()}')
print(f'É alfabético: {thing.isalpha()}')
print(f'É alfanumérico: {thing.isalnum()}')
print(f'Está em maiúsculo: {thing.isupper()}')
print(f'Está em minúsculo: {thing.islower()}')
print(f'Está capitalizada: {thing.istitle()}')